### PR TITLE
docs: add project mentions & a leaderboard

### PR DESCRIPTION
**Pull request by d-tatianin**

### CODE REVIEW

**Comment by oberrow** [comment]
Link:
https://github.com/OBOS-dev/obos
Score (KVM+q35):
[uACPI][INFO]: successfully loaded 1 AML blob, 1704 ops in 47ms (avg 35526/s)
Description:
"Hybrid Kernel with advanced driver loading"
CPU:
Intel i5-4570 (4) @ 3.600GHz

**Comment by ThatMishakov** [comment]
Link:
https://gitlab.com/mishakov/pmos
Score (KVM+q35, -smp 4):
[uACPI Log 3] successfully loaded 1 AML blob, 1726 ops in 2ms (avg 703007/s)
Description:
Microkernel-based operating system written from scratch with uACPI running in userspace
CPU:
AMD Ryzen 7 7840S (8) @ 3.30 GHz

**Comment by ilobilo** [comment]
Link:
https://github.com/ilobilo/ilobilix
Score (KVM+q35):
[info] successfully loaded 1 AML blob, 1705 ops in 1ms (avg 1294442/s)
Description:
Yet another monolithic/modular Linux clone wannabe. Currently under a rewrite. 
CPU:
AMD Ryzen 5 Pro 4640g (6/12) @ 3.7 GHz

**Comment by rayanmargham** [comment]
Link: https://github.com/rayanmargham/NyauxKC
Score (KVM+q35):
1835 ops in 101ms (avg 18009/s)

Description:
Nyaux is a monolithic UNIX-like multi-architecture kernel 

CPU:
Intel® Core™️ Ultra 7 265K

**Comment by Mathewnd** [comment]
Link: https://github.com/mathewnd/astral
Score (KVM+q35):
```
acpi: [info] successfully loaded 1 AML blob, 1705 ops in 0ms (avg 2411598/s)
```

Description:
```
Operating system written in C which aims be POSIX-compliant.
```

CPU:
```
Intel® Core™ i5-13600K 
```

**Comment by marv7000** [comment]
Link: https://github.com/menix-os/menix
Score (KVM+q35):
```
[    0.002290] [      0] acpi: successfully loaded 1 AML blob, 1708 ops in 1ms (avg 1359883/s)
```

Description:
```
A minimal and expandable Unix-like operating system.
```

CPU:
```
AMD Ryzen 7 7700X
```

**Comment by monkuous** [comment]
Link: https://github.com/proxima-os/proxima
Score (KVM+q35):
```
uacpi: info: successfully loaded 1 AML blob, 1705 ops in 0ms (avg 4635028/s)
```
Description:
```
A monolithic Unix-like operating system
```
CPU:
```
AMD Ryzen 7 5800X
```

**Pull request merged**
